import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto px-4 py-8 flex row-gap-8">
          <ul>
            <li> Public Routes</li>
            <li>
              <Link href="/" className="">Home Root</Link>
            </li>
            <li>
              <Link href="/0000/home">Home</Link>
            </li>
            <li>
              <Link href="/0000/projects">Projects</Link>
            </li>
            <li>
              <Link href="/0000/education">Education</Link>
            </li>
            <li>
              <Link href="/0000/tools">Tools</Link>
            </li>
            <li>
              <Link href="/0000/xps">XPS</Link>
            </li>
            <li>
              <Link href="/0000/contact">Contact</Link>
            </li>
            <li>
              <Link href="/not-found">Not Found</Link>
            </li>
            <li>
              <Link href="/auth/forgot-password">Forgot Password</Link>
            </li>
            <li>
              <Link href="/auth/access">Access</Link>
            </li>
            <li> Private Routes</li>
            <li>
              <Link href="/dashboard">Dashboard</Link>
            </li>
            <li>
              <Link href="/home">Home</Link>
            </li>
            <li>
              <Link href="/projects">Projects</Link>
            </li>
            <li>
              <Link href="/education">Education</Link>
            </li>
            <li>
              <Link href="/tools">Tools</Link>
            </li>
            <li>
              <Link href="/xps">XPS</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
          </ul>
          {children}
        </div>
      </body>
    </html>
  );
}
