import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto px-4 py-8 flex row-gap-8">
          <ul>
            <li> Public Routes</li>
            <li>
              <a href="/">Home Root</a>
            </li>
            <li>
              <a href="/0000/home">Home</a>
            </li>
            <li>
              <a href="/0000/projects">Projects</a>
            </li>
            <li>
              <a href="/0000/education">Education</a>
            </li>
            <li>
              <a href="/0000/tools">Tools</a>
            </li>
            <li>
              <a href="/0000/xps">XPS</a>
            </li>
            <li>
              <a href="/0000/contact">Contact</a>
            </li>
            <li>
              <a href="/not-found">Not Found</a>
            </li>
            <li>
              <a href="/auth/forgot-password">Forgot Password</a>
            </li>
            <li>
              <a href="/auth/access">Access</a>
            </li>
            <li> Private Routes</li>
            <li>
              <a href="/dashboard">Dashboard</a>
            </li>
            <li>
              <a href="/home">Home</a>
            </li>
            <li>
              <a href="/projects">Projects</a>
            </li>
            <li>
              <a href="/education">Education</a>
            </li>
            <li>
              <a href="/tools">Tools</a>
            </li>
            <li>
              <a href="/xps">XPS</a>
            </li>
            <li>
              <a href="/contact">Contact</a>
            </li>
          </ul>
          {children}
        </div>
      </body>
    </html>
  );
}
